### ISSUE TITLE
When the rokcetmq cluster network is slightly interrupted, the consumer will coredump

### ISSUE THREAD

**Issue by lvfuchao** [apache/rocketmq-client-cpp#197]
### the resulst as follow:
```
ubuntu:/data/core_files$ ls -rlth
-rw------- 1 root root 1.2G Oct 15 11:30 core-PullMsgTP-46073-1571110254
-rw------- 1 root root 773M Oct 15 11:32 core-PullMsgTP-40120-1571110324
-rw------- 1 root root 773M Oct 15 11:34 core-PullMsgTP-44259-1571110443
-rw------- 1 root root 773M Oct 15 11:35 core-PullMsgTP-48282-1571110505
-rw------- 1 root root 773M Oct 15 11:36 core-PullMsgTP-50684-1571110564
-rw------- 1 root root 773M Oct 15 11:38 core-PullMsgTP-54787-1571110683
```

### corefile as follow:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./k12_wb_wb_d -f /data/services/k12_wb_wb-2.0.8/conf/server.xml'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000080b208 in rocketmq::TcpRemotingClient::GetTransport(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
[Current thread is 1 (Thread 0x7f91dcfe9700 (LWP 54826))]
(gdb) bt
#0  0x000000000080b208 in rocketmq::TcpRemotingClient::GetTransport(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#1  0x000000000080bbf6 in rocketmq::TcpRemotingClient::invokeSync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocketmq::RemotingCommand&, int) ()
#2  0x00000000007d0ecc in rocketmq::MQClientAPIImpl::lockBatchMQ(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocketmq::LockBatchRequestBody*, std::vector<rocketmq::MQMessageQueue, std::allocator<rocketmq::MQMessageQueue> >&, int, rocketmq::SessionCredentials const&) ()
#3  0x000000000079c453 in rocketmq::Rebalance::lock(rocketmq::MQMessageQueue) ()
#4  0x000000000078305b in rocketmq::DefaultMQPushConsumer::pullMessageAsync(rocketmq::PullRequest*) ()
#5  0x00000000007c8c11 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf2<void, rocketmq::taskBatchHandler, rocketmq::Task, long>, boost::_bi::list3<boost::_bi::value<rocketmq::taskBatchHandler*>, boost::_bi::value<rocketmq::Task>, boost::_bi::value<long> > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
#6  0x0000000000778e32 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#7  0x00000000007c9c18 in boost::asio::io_context::run() ()
#8  0x000000000086bc4d in thread_proxy ()
#9  0x00007f920fff86fa in start_thread (arg=0x7f91dcfe9700) at pthread_create.c:333
#10 0x00007f920f081b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

**Comment by ifplusor** [comment]
The version(rocketmq-client-cpp-1.2.0) has some bugs in network layer, please use latest version.
And I maintain another branch, I hope you will try it out. The repo is: https://github.com/ifplusor/rocketmq-client-cpp/tree/re-dev

**Comment by lvfuchao** [comment]
ok thanks
